<?xml version="1.0"?>
<package format="3">
  <name>robot_mapping</name>
  <version>0.1.0</version>
  <description>Unified robot workspace robot_mapping</description>
  <maintainer email="dori@example.com">dori</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>cartographer_ros</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>sllidar_ros2</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
